# name         lanes                                  alias     index    speed     fec
Ethernet0      0                                      etp1a     1        25000     none
Ethernet1      1                                      etp1b     1        25000     none
Ethernet2      2                                      etp1c     1        25000     none
Ethernet3      3                                      etp1d     1        25000     none
Ethernet8      8                                      etp2a     2        25000     none
Ethernet9      9                                      etp2b     2        25000     none
Ethernet10     10                                     etp2c     2        25000     none
Ethernet11     11                                     etp2d     2        25000     none
Ethernet16     16                                     etp3a     3        25000     none
Ethernet17     17                                     etp3b     3        25000     none
Ethernet18     18                                     etp3c     3        25000     none
Ethernet19     19                                     etp3d     3        25000     none
Ethernet24     24                                     etp4a     4        25000     none
Ethernet25     25                                     etp4b     4        25000     none
Ethernet26     26                                     etp4c     4        25000     none
Ethernet27     27                                     etp4d     4        25000     none
Ethernet32     32                                     etp5a     5        25000     none
Ethernet33     33                                     etp5b     5        25000     none
Ethernet34     34                                     etp5c     5        25000     none
Ethernet35     35                                     etp5d     5        25000     none
Ethernet40     40                                     etp6a     6        25000     none
Ethernet41     41                                     etp6b     6        25000     none
Ethernet42     42                                     etp6c     6        25000     none
Ethernet43     43                                     etp6d     6        25000     none
Ethernet48     48                                     etp7a     7        25000     none
Ethernet49     49                                     etp7b     7        25000     none
Ethernet50     50                                     etp7c     7        25000     none
Ethernet51     51                                     etp7d     7        25000     none
Ethernet56     56                                     etp8a     8        25000     none
Ethernet57     57                                     etp8b     8        25000     none
Ethernet58     58                                     etp8c     8        25000     none
Ethernet59     59                                     etp8d     8        25000     none
Ethernet64     64                                     etp9a     9        25000     none
Ethernet65     65                                     etp9b     9        25000     none
Ethernet66     66                                     etp9c     9        25000     none
Ethernet67     67                                     etp9d     9        25000     none
Ethernet72     72                                     etp10a    10       25000     none
Ethernet73     73                                     etp10b    10       25000     none
Ethernet74     74                                     etp10c    10       25000     none
Ethernet75     75                                     etp10d    10       25000     none
Ethernet80     80                                     etp11a    11       25000     none
Ethernet81     81                                     etp11b    11       25000     none
Ethernet82     82                                     etp11c    11       25000     none
Ethernet83     83                                     etp11d    11       25000     none
Ethernet88     88                                     etp12a    12       25000     none
Ethernet89     89                                     etp12b    12       25000     none
Ethernet90     90                                     etp12c    12       25000     none
Ethernet91     91                                     etp12d    12       25000     none
Ethernet96     96,97,98,99,100,101,102,103            etp13     13       400000    rs
Ethernet104    104,105,106,107,108,109,110,111        etp14     14       400000    rs
Ethernet112    112,113,114,115,116,117,118,119        etp15     15       400000    rs
Ethernet120    120,121,122,123,124,125,126,127        etp16     16       400000    rs
Ethernet128    128                                    etp17a    17       25000     none
Ethernet129    129                                    etp17b    17       25000     none
Ethernet130    130                                    etp17c    17       25000     none
Ethernet131    131                                    etp17d    17       25000     none
Ethernet136    136                                    etp18a    18       25000     none
Ethernet137    137                                    etp18b    18       25000     none
Ethernet138    138                                    etp18c    18       25000     none
Ethernet139    139                                    etp18d    18       25000     none
Ethernet144    144                                    etp19a    19       25000     none
Ethernet145    145                                    etp19b    19       25000     none
Ethernet146    146                                    etp19c    19       25000     none
Ethernet147    147                                    etp19d    19       25000     none
Ethernet152    152                                    etp20a    20       25000     none
Ethernet153    153                                    etp20b    20       25000     none
Ethernet154    154                                    etp20c    20       25000     none
Ethernet155    155                                    etp20d    20       25000     none
Ethernet160    160                                    etp21a    21       25000     none
Ethernet161    161                                    etp21b    21       25000     none
Ethernet162    162                                    etp21c    21       25000     none
Ethernet163    163                                    etp21d    21       25000     none
Ethernet168    168                                    etp22a    22       25000     none
Ethernet169    169                                    etp22b    22       25000     none
Ethernet170    170                                    etp22c    22       25000     none
Ethernet171    171                                    etp22d    22       25000     none
Ethernet176    176                                    etp23a    23       25000     none
Ethernet177    177                                    etp23b    23       25000     none
Ethernet178    178                                    etp23c    23       25000     none
Ethernet179    179                                    etp23d    23       25000     none
Ethernet184    184                                    etp24a    24       25000     none
Ethernet185    185                                    etp24b    24       25000     none
Ethernet186    186                                    etp24c    24       25000     none
Ethernet187    187                                    etp24d    24       25000     none
Ethernet192    192                                    etp25a    25       25000     none
Ethernet193    193                                    etp25b    25       25000     none
Ethernet194    194                                    etp25c    25       25000     none
Ethernet195    195                                    etp25d    25       25000     none
Ethernet200    200                                    etp26a    26       25000     none
Ethernet201    201                                    etp26b    26       25000     none
Ethernet202    202                                    etp26c    26       25000     none
Ethernet203    203                                    etp26d    26       25000     none
Ethernet208    208                                    etp27a    27       25000     none
Ethernet209    209                                    etp27b    27       25000     none
Ethernet210    210                                    etp27c    27       25000     none
Ethernet211    211                                    etp27d    27       25000     none
Ethernet216    216                                    etp28a    28       25000     none
Ethernet217    217                                    etp28b    28       25000     none
Ethernet218    218                                    etp28c    28       25000     none
Ethernet219    219                                    etp28d    28       25000     none
Ethernet224    224,225,226,227,228,229,230,231        etp29     29       400000    none
Ethernet232    232,233,234,235,236,237,238,239        etp30     30       400000    none
Ethernet240    240,241,242,243,244,245,246,247        etp31     31       400000    none
Ethernet248    248,249,250,251,252,253,254,255        etp32     32       400000    none
