# Console configuration for NVIDIA AST2700 BMC platform
# linuxargs: console=ttyS12,115200n8 earlycon (see platform/aspeed/scripts/sonic-uboot-env-init.sh)
CONSOLE_DEV=12
CONSOLE_SPEED=115200
EARLYCON="earlycon"

# Variable log size(MB)
VAR_LOG_SIZE=512

# Additional kernel command line arguments
ONIE_PLATFORM_EXTRA_CMDLINE_LINUX=""

bootconf="sonic-ast2700-nvidia-spc6-bmc"
