# Nokia platforms
NOKIA_BMC_H6_128_PLATFORM_VERSION = 1.0
export NOKIA_BMC_H6_128_PLATFORM_VERSION
NOKIA_BMC_H6_128_PLATFORM_MODULE = sonic-platform-aspeed-nokia-h6-128_$(NOKIA_BMC_H6_128_PLATFORM_VERSION)_$(CONFIGURED_ARCH).deb
$(NOKIA_BMC_H6_128_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-nokia
$(NOKIA_BMC_H6_128_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON) $(ASPEED_COMMON_PLATFORM_MODULE)
$(NOKIA_BMC_H6_128_PLATFORM_MODULE)_PLATFORM = arm64-nokia_bmc_h6_128-r0

MPATH       := $($(NOKIA_BMC_H6_128_PLATFORM_MODULE)_SRC_PATH)
DEP_FILES   := $(SONIC_COMMON_FILES_LIST) platform/aspeed/platform-modules-nokia.mk
DEP_FILES   += $(SONIC_COMMON_BASE_FILES_LIST)
DEP_FILES   += $(shell git ls-files $(MPATH))

$(NOKIA_BMC_H6_128_PLATFORM_MODULE)_CACHE_MODE  := GIT_CONTENT_SHA
$(NOKIA_BMC_H6_128_PLATFORM_MODULE)_DEP_FLAGS   := $(SONIC_COMMON_FLAGS_LIST)
$(NOKIA_BMC_H6_128_PLATFORM_MODULE)_DEP_FILES   := $(DEP_FILES)
SONIC_DPKG_DEBS += $(NOKIA_BMC_H6_128_PLATFORM_MODULE)
