# name            lanes                                    alias      index        speed         admin_status    fec
Ethernet0         1,2,3,4                                  etp1      1            400000        down            rs
Ethernet1         5,6,7,8                                  etp2      2            400000        down            rs
Ethernet2         9,10,11,12                               etp3      3            400000        down            rs
Ethernet3         13,14,15,16                              etp4      4            400000        down            rs
Ethernet4         17,18,19,20                              etp5      5            400000        down            rs
Ethernet5         21,22,23,24                              etp6      6            400000        down            rs
Ethernet6         25,26,27,28                              etp7      7            400000        down            rs
Ethernet7         29,30,31,32                              etp8      8            400000        down            rs
Ethernet8         33,34,35,36                              etp9      9            400000        down            rs
Ethernet9         37,38,39,40                              etp10     10           400000        down            rs
Ethernet10        41,42,43,44                              etp11     11           400000        down            rs
Ethernet11        45,46,47,48                              etp12     12           400000        down            rs
Ethernet12        49,50,51,52                              etp13     13           400000        down            rs
Ethernet13        53,54,55,56                              etp14     14           400000        down            rs
Ethernet14        57,58,59,60                              etp15     15           400000        down            rs
Ethernet15        61,62,63,64                              etp16     16           400000        down            rs
Ethernet16        65,66,67,68                              etp17     17           400000        down            rs
Ethernet17        69,70,71,72                              etp18     18           400000        down            rs
Ethernet18        73,74,75,76                              etp19     19           400000        down            rs
Ethernet19        77,78,79,80                              etp20     20           400000        down            rs
Ethernet20        81,82,83,84                              etp21     21           400000        down            rs
Ethernet21        85,86,87,88                              etp22     22           400000        down            rs
Ethernet22        89,90,91,92                              etp23     23           400000        down            rs
Ethernet23        93,94,95,96                              etp24     24           400000        down            rs
Ethernet24        97,98,99,100                             etp25     25           400000        down            rs
Ethernet25        101,102,103,104                          etp26     26           400000        down            rs
Ethernet26        105,106,107,108                          etp27     27           400000        down            rs
Ethernet27        109,110,111,112                          etp28     28           400000        down            rs
Ethernet28        113,114,115,116                          etp29     29           400000        down            rs
Ethernet29        117,118,119,120                          etp30     30           400000        down            rs
Ethernet30        121,122,123,124                          etp31     31           400000        down            rs
Ethernet31        125,126,127,128                          etp32     32           400000        down            rs
Ethernet32        129,130,131,132                          etp33     33           400000        down            rs
Ethernet33        133,134,135,136                          etp34     34           400000        down            rs
Ethernet34        137,138,139,140                          etp35     35           400000        down            rs
Ethernet35        141,142,143,144                          etp36     36           400000        down            rs
Ethernet36        145,146,147,148                          etp37     37           400000        down            rs
Ethernet37        149,150,151,152                          etp38     38           400000        down            rs
Ethernet38        153,154,155,156                          etp39     39           400000        down            rs
Ethernet39        157,158,159,160                          etp40     40           400000        down            rs
Ethernet40        161,162,163,164                          etp41     41           400000        down            rs
Ethernet41        165,166,167,168                          etp42     42           400000        down            rs
Ethernet42        169,170,171,172                          etp43     43           400000        down            rs
Ethernet43        173,174,175,176                          etp44     44           400000        down            rs
Ethernet44        177,178,179,180                          etp45     45           400000        down            rs
Ethernet45        181,182,183,184                          etp46     46           400000        down            rs
Ethernet46        185,186,187,188                          etp47     47           400000        down            rs
Ethernet47        189,190,191,192                          etp48     48           400000        down            rs
Ethernet48        193,194,195,196                          etp49     49           400000        down            rs
Ethernet49        197,198,199,200                          etp50     50           400000        down            rs
Ethernet50        201,202,203,204                          etp51     51           400000        down            rs
Ethernet51        205,206,207,208                          etp52     52           400000        down            rs
Ethernet52        209,210,211,212                          etp53     53           400000        down            rs
Ethernet53        213,214,215,216                          etp54     54           400000        down            rs
Ethernet54        217,218,219,220                          etp55     55           400000        down            rs
Ethernet55        221,222,223,224                          etp56     56           400000        down            rs
Ethernet56        225,226,227,228                          etp57     57           400000        down            rs
Ethernet57        229,230,231,232                          etp58     58           400000        down            rs
Ethernet58        233,234,235,236                          etp59     59           400000        down            rs
Ethernet59        237,238,239,240                          etp60     60           400000        down            rs
Ethernet60        241,242,243,244                          etp61     61           400000        down            rs
Ethernet61        245,246,247,248                          etp62     62           400000        down            rs
Ethernet62        249,250,251,252                          etp63     63           400000        down            rs
Ethernet63        253,254,255,256                          etp64     64           400000        down            rs
Ethernet64        257,258,259,260                          etp65     65           400000        down            rs
Ethernet65        261,262,263,264                          etp66     66           400000        down            rs
Ethernet66        265,266,267,268                          etp67     67           400000        down            rs
Ethernet67        269,270,271,272                          etp68     68           400000        down            rs
Ethernet68        273,274,275,276                          etp69     69           400000        down            rs
Ethernet69        277,278,279,280                          etp70     70           400000        down            rs
Ethernet70        281,282,283,284                          etp71     71           400000        down            rs
Ethernet71        285,286,287,288                          etp72     72           400000        down            rs
Ethernet72        289,290,291,292                          etp73     73           400000        down            rs
Ethernet73        293,294,295,296                          etp74     74           400000        down            rs
Ethernet74        297,298,299,300                          etp75     75           400000        down            rs
Ethernet75        301,302,303,304                          etp76     76           400000        down            rs
Ethernet76        305,306,307,308                          etp77     77           400000        down            rs
Ethernet77        309,310,311,312                          etp78     78           400000        down            rs
Ethernet78        313,314,315,316                          etp79     79           400000        down            rs
Ethernet79        317,318,319,320                          etp80     80           400000        down            rs
Ethernet80        321,322,323,324                          etp81     81           400000        down            rs
Ethernet81        325,326,327,328                          etp82     82           400000        down            rs
Ethernet82        329,330,331,332                          etp83     83           400000        down            rs
Ethernet83        333,334,335,336                          etp84     84           400000        down            rs
Ethernet84        337,338,339,340                          etp85     85           400000        down            rs
Ethernet85        341,342,343,344                          etp86     86           400000        down            rs
Ethernet86        345,346,347,348                          etp87     87           400000        down            rs
Ethernet87        349,350,351,352                          etp88     88           400000        down            rs
Ethernet88        353,354,355,356                          etp89     89           400000        down            rs
Ethernet89        357,358,359,360                          etp90     90           400000        down            rs
Ethernet90        361,362,363,364                          etp91     91           400000        down            rs
Ethernet91        365,366,367,368                          etp92     92           400000        down            rs
Ethernet92        369,370,371,372                          etp93     93           400000        down            rs
Ethernet93        373,374,375,376                          etp94     94           400000        down            rs
Ethernet94        377,378,379,380                          etp95     95           400000        down            rs
Ethernet95        381,382,383,384                          etp96     96           400000        down            rs
Ethernet96        385,386,387,388                          etp97     97           400000        down            rs
Ethernet97        389,390,391,392                          etp98     98           400000        down            rs
Ethernet98        393,394,395,396                          etp99     99           400000        down            rs
Ethernet99        397,398,399,400                          etp100    100          400000        down            rs
Ethernet100       401,402,403,404                          etp101    101          400000        down            rs
Ethernet101       405,406,407,408                          etp102    102          400000        down            rs
Ethernet102       409,410,411,412                          etp103    103          400000        down            rs
Ethernet103       413,414,415,416                          etp104    104          400000        down            rs
Ethernet104       417,418,419,420                          etp105    105          400000        down            rs
Ethernet105       421,422,423,424                          etp106    106          400000        down            rs
Ethernet106       425,426,427,428                          etp107    107          400000        down            rs
Ethernet107       429,430,431,432                          etp108    108          400000        down            rs
Ethernet108       433,434,435,436                          etp109    109          400000        down            rs
Ethernet109       437,438,439,440                          etp110    110          400000        down            rs
Ethernet110       441,442,443,444                          etp111    111          400000        down            rs
Ethernet111       445,446,447,448                          etp112    112          400000        down            rs
Ethernet112       449,450,451,452                          etp113    113          400000        down            rs
Ethernet113       453,454,455,456                          etp114    114          400000        down            rs
Ethernet114       457,458,459,460                          etp115    115          400000        down            rs
Ethernet115       461,462,463,464                          etp116    116          400000        down            rs
Ethernet116       465,466,467,468                          etp117    117          400000        down            rs
Ethernet117       469,470,471,472                          etp118    118          400000        down            rs
Ethernet118       473,474,475,476                          etp119    119          400000        down            rs
Ethernet119       477,478,479,480                          etp120    120          400000        down            rs
Ethernet120       481,482,483,484                          etp121    121          400000        down            rs
Ethernet121       485,486,487,488                          etp122    122          400000        down            rs
Ethernet122       489,490,491,492                          etp123    123          400000        down            rs
Ethernet123       493,494,495,496                          etp124    124          400000        down            rs
Ethernet124       497,498,499,500                          etp125    125          400000        down            rs
Ethernet125       501,502,503,504                          etp126    126          400000        down            rs
Ethernet126       505,506,507,508                          etp127    127          400000        down            rs
Ethernet127       509,510,511,512                          etp128    128          400000        down            rs
