# Console configuration is handled in platform_arm64.conf via kernel cmdline
ONIE_PLATFORM_EXTRA_CMDLINE_LINUX=""
CONSOLE_SPEED=115200
CONSOLE_DEV=12
bootconf="nokia-h6-128-r0"
VAR_LOG=512
EARLYCON="earlycon=uart8250,mmio32,0x14c33b00"
