# docker image for docker-telemetry-sidecar

DOCKER_TELEMETRY_SIDECAR_STEM = docker-telemetry-sidecar
DOCKER_TELEMETRY_SIDECAR = $(DOCKER_TELEMETRY_SIDECAR_STEM).gz
DOCKER_TELEMETRY_SIDECAR_DBG = $(DOCKER_TELEMETRY_SIDECAR_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_TELEMETRY_SIDECAR)_LOAD_DOCKERS = $(DOCKER_CONFIG_ENGINE_TRIXIE)

$(DOCKER_TELEMETRY_SIDECAR)_PATH = $(DOCKERS_PATH)/$(DOCKER_TELEMETRY_SIDECAR_STEM)

$(DOCKER_TELEMETRY_SIDECAR)_VERSION = 1.0.0
$(DOCKER_TELEMETRY_SIDECAR)_PACKAGE_NAME = telemetry-sidecar

SONIC_DOCKER_IMAGES += $(DOCKER_TELEMETRY_SIDECAR)
SONIC_TRIXIE_DOCKERS += $(DOCKER_TELEMETRY_SIDECAR)

SONIC_DOCKER_DBG_IMAGES += $(DOCKER_TELEMETRY_SIDECAR_DBG)
SONIC_TRIXIE_DBG_DOCKERS += $(DOCKER_TELEMETRY_SIDECAR_DBG)

$(DOCKER_TELEMETRY_SIDECAR)_DEPENDS += $(LIBSWSSCOMMON)

$(DOCKER_TELEMETRY_SIDECAR)_PYTHON_WHEELS += $(SONIC_PY_COMMON_PY3)

$(DOCKER_TELEMETRY_SIDECAR)_INSTALL_PYTHON_WHEELS = $(SONIC_PY_COMMON_PY3)

$(DOCKER_TELEMETRY_SIDECAR)_INSTALL_DEBS = $(LIBSWSSCOMMON) \
                                           $(PYTHON3_SWSSCOMMON) \
                                           $(LIBYANG3_PY3)

$(DOCKER_TELEMETRY_SIDECAR)_CONTAINER_NAME = telemetry-sidecar

$(DOCKER_TELEMETRY_SIDECAR)_FILES += $(CONTAINER_CHECKER)
$(DOCKER_TELEMETRY_SIDECAR)_FILES += $(SERVICE_CHECKER_PY)
$(DOCKER_TELEMETRY_SIDECAR)_FILES += $(TELEMETRY_SYSTEMD)
$(DOCKER_TELEMETRY_SIDECAR)_FILES += $(K8S_POD_CONTROL)

